name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: 'Restore dependencies'
      run: dotnet restore
      
    - name: 'Build the project'
      run: dotnet build --configuration Release --no-restore
      
    - name: 'Publish the project'
      run: dotnet publish --configuration Release --no-build --output ./publish
      
    - name: 'Check if publish profile secret exists'
      run: |
        if [ -z "${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}" ]; then
          echo "ERROR: AZURE_WEBAPP_PUBLISH_PROFILE secret is empty or not set"
          exit 1
        else
          echo "Publish profile secret is set (length: ${#PUBLISH_PROFILE})"
        fi
      env:
        PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'Rotations'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './publish'

