name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: 'Restore dependencies'
      run: dotnet restore
      
    - name: 'Build the project'
      run: dotnet build --configuration Release --no-restore
      
    - name: 'Publish the project'
      run: dotnet publish --configuration Release --no-build --output ./publish
      
    - name: 'Create deployment ZIP'
      run: cd publish && zip -r ../deployment.zip . && cd ..
      
    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - name: 'Deploy to Azure Web App using Azure CLI'
      run: |
        az webapp deploy \
          --name Rotations \
          --resource-group Inet_Partner_Resource_Group \
          --src-path ./deployment.zip \
          --type zip

