name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: 'Restore dependencies'
      run: dotnet restore MyAzureWebApp/MyAzureWebApp.csproj
      
    - name: 'Build the project'
      run: dotnet build MyAzureWebApp/MyAzureWebApp.csproj --configuration Release --no-restore
      
    - name: 'Publish the project'
      run: dotnet publish MyAzureWebApp/MyAzureWebApp.csproj --configuration Release --no-build --output ./publish
      
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Rotations'  # Din eksisterende Azure Web App
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: './publish'

